### ISSUE TITLE
Flapping Alerts

### ISSUE THREAD

**Issue by marcusboden** [canonical/hardware-observer-operator#476]
Some of the alerts from this charm tend to be flapping a lot. The CollectorFailed alert is prone this, because it's very dependent on the hardware of the BMC, which tend to be flaky. This results in really annoying, flapping alerts, if the BMC doesn't respond in time.

Can we improve the alertrule by adding the `keep_firing_for` option and have it always at least fire for an hour? 
From the [docs](https://prometheus.io/docs/prometheus/latest/configuration/alerting_rules/#defining-alerting-rules):
> There is also an optional keep_firing_for clause that tells Prometheus to keep this alert firing for the specified duration after the firing condition was last met. This can be used to prevent situations such as flapping alerts, false resolutions due to lack of data loss, etc. Alerting rules without the keep_firing_for clause will deactivate on the first evaluation where the condition is not met (assuming any optional for duration described above has been satisfied).

**Comment by marcusboden** [comment]
> From my understanding the keep_firing_for won't reduce the noise because it will keep alerting event that the collector back to normal.

Yes, that's exactly what I want. The issue is that some of the collectors response time hover around the timeout time, resulting in e.g. 20% of the metric missing, which in turn triggers some alerts sometimes (if it happens longer than 5min by chance), but most of the time not. But it's super annoying and hard to silence, as the moment you look in alertmanager, they are resolved already and you have to build the correct set of tags for the silence from memory.

However, I also agree that we should increase the `for:` part to 30 min. We usually don't really care if the IPMI doesn't return perfectly on time every few minutes. 

Small addendum: I already tried to define my own alert for that [here](https://github.com/canonical/prometheus-k8s-operator/issues/746), but there may be a bug with the `keep_firing_for` in the cos library. Just as a heads-up, you may run into this as well.

**Comment by gabrielcocenza** [comment]
Just an update. cos-tool has updated the Prometheus module, however they are still not available at prometheus 1/stable or 2/stable
